driver:
  name: vagrant

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: ubuntu-16.04
  - name: mvbcoding/awslinux

provisioner:
  name: salt_solo
  formula: graphite
  pillars-from-files:
    graphite.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - graphite

suites:
  - name: server
    provisioner:
      state_top:
        base:
          '*':
            - graphite

verifier:
  name: shell
  command: testinfra -vvv --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
